# Generated by Django 3.2.9 on 2021-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211125_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitemparagraph',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='info1_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='info2_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='info3_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='info4_text',
            field=models.TextField(blank=True),
        ),
    ]
